spring:
  application:
    name: library_management_be

  datasource:
    url: jdbc:mysql://localhost:3306/library_management?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

app:
  jwt:
    secret-key: 1cbaee3794baa86215098188f54d3adaaefc3c7b49ed28dc475cc29a4ac4fe05
    expiration-ms: 86400000 # 1 day in milliseconds
    refresh-token-expiration-ms: 604800000 # 7 days in milliseconds